# Generated by Django 4.1.5 on 2023-01-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_entry_example_userprogress_remove_word_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
