# Generated by Django 4.1.5 on 2023-01-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_example_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.word"
            ),
        ),
    ]
