# Generated by Django 4.1.5 on 2023-07-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.classgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='entryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.entry')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.abstractstudent')),
            ],
        ),
        migrations.CreateModel(
            name='entryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classgroup')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.entry')),
            ],
        ),
    ]
